[connections.snowflake]
account = "ZUOFYPT-EJB20660"
user = "leonardkriese"
password = "^U@AiLca2#ixQN"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true